<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>billing_email</name>
   <tag></tag>
   <elementGuidId>cb07b42d-b20c-4226-983d-eecdac9b16b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ffc8e8e-343f-462e-96ce-b0c0b6768e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>052181e8-bf62-4696-8954-2b6edc2fee12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>0214fe77-6557-42cd-8455-65f99b99a0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_email</value>
      <webElementGuid>10625f5c-c6c4-4fb2-aa16-a8c48d9b9888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_email</value>
      <webElementGuid>5e254ab5-b8b2-4cf2-b1dd-05e80ab10a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email username</value>
      <webElementGuid>ae13fd50-db2c-4ec8-812d-cb0e145fb0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_email&quot;)</value>
      <webElementGuid>ff66c960-6503-47e0-ba14-1feac7b2e289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_email']</value>
      <webElementGuid>5fe4ae0d-5b16-4340-9d15-8ef7be66bae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_email_field']/span/input</value>
      <webElementGuid>96349124-94fc-41ee-8f8d-38446fd2a590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[11]/span/input</value>
      <webElementGuid>9b7c5906-90ec-4cee-9a97-58e1f271fca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'billing_email' and @id = 'billing_email']</value>
      <webElementGuid>8f3b971f-2a1b-42ee-b21a-2b6471793a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
