<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer_firstname</name>
   <tag></tag>
   <elementGuidId>185bf21b-b3b4-4bb4-8272-d769bbc059d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f89d5957-b28b-471e-bd74-1f61da1b1aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>$('#firstname').val(this.value);</value>
      <webElementGuid>3202b3a3-a430-4bb5-be7c-42be8dfdec96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d3f9c7a-9263-4906-9670-8743bc4d9f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is_required validate form-control</value>
      <webElementGuid>9be23e63-5c31-480e-bfe4-b102312efbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>isName</value>
      <webElementGuid>7177e033-784a-492d-a810-a2a21611d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_firstname</value>
      <webElementGuid>81051fdb-cd74-4128-ba0a-6eb9f4a8b094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_firstname</value>
      <webElementGuid>3da32a1e-ff7f-4fe7-b3f9-dec452e6fe1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_firstname&quot;)</value>
      <webElementGuid>1ae47fdb-432d-4952-b45f-eef3866ab874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_firstname']</value>
      <webElementGuid>c556fdbf-1ad6-4969-9bef-4b048e32b6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div[2]/input</value>
      <webElementGuid>b4dce6f6-4571-447b-b94a-5a338531f89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>54907e9f-cb8f-4525-9a8e-ca756e5fbf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer_firstname' and @name = 'customer_firstname']</value>
      <webElementGuid>1b8c1584-80e2-49e7-9899-4526e491cf4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
