<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Day</name>
   <tag></tag>
   <elementGuidId>8f456c2a-5325-4325-bb51-e49bc209242a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select#days</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '
						-
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													
						
					' or . = '
						-
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													
						
					')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='days']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a290c63e-8b02-41e7-b17a-526f3e2fa304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-4</value>
      <webElementGuid>57cfe720-6df7-4e26-a8ba-176220d74771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						-
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													
						
					</value>
      <webElementGuid>f27a882c-15aa-49ce-ae59-082a1ea2e30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-creation_form&quot;)/div[@class=&quot;account_creation&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]</value>
      <webElementGuid>fe1cdce4-4a41-4a82-9cd6-1f14c5e1df2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div[6]/div/div</value>
      <webElementGuid>99ce3eae-9917-4c9b-94d2-d42e01c28b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[2]</value>
      <webElementGuid>552307dd-09cf-4d12-a04e-4c0916c28253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Five characters minimum)'])[1]/following::div[3]</value>
      <webElementGuid>72a9bf3b-7c7a-433c-be58-b4aafac56a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/preceding::div[2]</value>
      <webElementGuid>4b26b467-41dd-490a-914d-d451a46e6cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>22544be8-5048-461d-9019-e02c9c299b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
						-
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													
						
					' or . = '
						-
							-
															1  
															2  
															3  
															4  
															5  
															6  
															7  
															8  
															9  
															10  
															11  
															12  
															13  
															14  
															15  
															16  
															17  
															18  
															19  
															20  
															21  
															22  
															23  
															24  
															25  
															26  
															27  
															28  
															29  
															30  
															31  
													
						
					')]</value>
      <webElementGuid>0f00f6c4-0d27-4ff9-ac40-59dfa7102bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
